rem *** Randomized Customization Items. This replaces kit parts and also remains on soldiers after death. ***

rem *** Pets ***
ObjectTemplate.addTemplate bri_PetItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** BackPacks ***
ObjectTemplate.addTemplate Bri_BackPackItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** Helmets ***
ObjectTemplate.addTemplate Bri_HelmetItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** Face Items ***
ObjectTemplate.addTemplate bri_FaceItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** Waist Items ***
ObjectTemplate.addTemplate bri_WaistItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** Feet Items ***
ObjectTemplate.addTemplate bri_FeetItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3
