rem *** Randomized Customization Items. This replaces kit parts and also remains on soldiers after death. ***

rem *** Rippin Rocket/TurboJet specific layout. This doesn't include certain items like back packs ete. ***
rem *** This is to avoid overlapping customization items that would conflict with the Rippin Rocket/TurboJet items. ***

rem *** Pets ***
ObjectTemplate.addTemplate bri_PetItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3
