rem
rem *** Moonraker Laser from GoldenEye 007
rem
rem AnimationStateMachine.copyState2 Moonraker v_arg1

rem
rem *** Desert Combat Weapon Animations ***
rem
AnimationStateMachine.copyState2 M249 v_arg1
AnimationStateMachine.copyState2 AK47 v_arg1
AnimationStateMachine.copyState2 M16 v_arg1


rem
rem  *** BFH Weapons ***
rem
AnimationStateMachine.copyState2 BRI_SMG_Thompson v_arg1
AnimationStateMachine.copyState2 GER_SMG_MP40 v_arg1
AnimationStateMachine.copyState2 GER_MG_MG40 v_arg1
AnimationStateMachine.copyState2 BRI_MG_Lewis v_arg1
AnimationStateMachine.copyState2 GER_MG_BC2 v_arg1
AnimationStateMachine.copyState2 BRI_MG_BC2 v_arg1
AnimationStateMachine.copyState2 bri_smg_bc2 v_arg1
AnimationStateMachine.copyState2 ger_smg_bc2 v_arg1



AnimationStateMachine.copyState BRI_SMG_Thompson v_arg1 Thompson 1.0 Thompson 1.0
AnimationStateMachine.copyState GER_SMG_MP40 v_arg1 Mp40 1.0 Mp40 1.0

AnimationStateMachine.copyState GER_MG_MG40 v_arg1 M249 1.0 M249 1.0
AnimationStateMachine.copyState BRI_MG_Lewis v_arg1 M249 1.0 M249 1.0

AnimationStateMachine.copyState GER_MG_BC2 v_arg1 M249 1.0 M249 1.0
AnimationStateMachine.copyState BRI_MG_BC2 v_arg1 M249 1.0 M249 1.0


AnimationStateMachine.copyState bri_smg_bc2 v_arg1 Thompson 1.0 Thompson 1.0
AnimationStateMachine.copyState ger_smg_bc2 v_arg1 Thompson 1.0 Thompson 1.0