AnimationStateMachine.copyState2 COM_TNT v_arg1 
AnimationStateMachine.copyState2 explosivetrap_bri v_arg1
AnimationStateMachine.copyState2 explosivetrap_ger v_arg1
AnimationStateMachine.copyState2 ExplosiveKeg v_arg1
AnimationStateMachine.copyState2 bri_at_rifle v_arg1
AnimationStateMachine.copyState2 ger_at_rifle v_arg1
AnimationStateMachine.copyState2 BRI_Sniperrifle_LeeEnfield v_arg1
AnimationStateMachine.copyState2 GER_SniperRifle_Gewehr43 v_arg1
AnimationStateMachine.copyState2 NASupplyDrop v_arg1
AnimationStateMachine.copyState2 bri_supplydrop v_arg1
AnimationStateMachine.copyState2 ger_supplydrop v_arg1
AnimationStateMachine.copyState2 bri_landmine v_arg1 
AnimationStateMachine.copyState2 ger_landmine v_arg1 
AnimationStateMachine.copyState2 bri_pistol_agent v_arg1
AnimationStateMachine.copyState2 ger_pistol_agent v_arg1
AnimationStateMachine.copyState2 bri_pistol_agent_slot2 v_arg1
AnimationStateMachine.copyState2 ger_pistol_agent_slot2 v_arg1
AnimationStateMachine.copyState2 BRI_Pistol_Colt v_arg1
AnimationStateMachine.copyState2 GER_Pistol_Luger v_arg1
AnimationStateMachine.copyState2 BRI_Shotgun v_arg1
AnimationStateMachine.copyState2 GER_Shotgun v_arg1
AnimationStateMachine.copyState2 BRI_GrenadeSpam v_arg1
AnimationStateMachine.copyState2 GER_GrenadeSpam v_arg1
AnimationStateMachine.copyState2 BRI_AT_PIAT v_arg1
AnimationStateMachine.copyState2 GER_AT_PanzerFaust v_arg1
AnimationStateMachine.copyState2 bri_aa_stinger v_arg1
AnimationStateMachine.copyState2 ger_aa_strela v_arg1
AnimationStateMachine.copyState2 bri_miniTankKeg v_arg1
AnimationStateMachine.copyState2 ger_miniTankKeg v_arg1
AnimationStateMachine.copyState2 ger_miniTankKeg v_arg1
AnimationStateMachine.copyState2 ger_miniTankKeg v_arg1
AnimationStateMachine.copyState2 bri_vehicledrop v_arg1
AnimationStateMachine.copyState2 ger_vehicledrop v_arg1
AnimationStateMachine.copyState2 SmokeGrenade v_arg1
AnimationStateMachine.copyState2 ProximityMine v_arg1


AnimationStateMachine.copyState explosivetrap_bri v_arg1 ExpPack 1.0 ExpPack 1.0
AnimationStateMachine.copyState explosivetrap_ger v_arg1 ExpPack 1.0 ExpPack 1.0

AnimationStateMachine.copyState ExplosiveKeg v_arg1 GrenadeAllies 1.0 GrenadeAllies 1.0

AnimationStateMachine.copyState BRI_GrenadeSpam v_arg1 GrenadeAllies 1.0 GrenadeAllies 1.0
AnimationStateMachine.copyState GER_GrenadeSpam v_arg1 GrenadeAxis 1.0 GrenadeAxis 1.0

AnimationStateMachine.copyState bri_miniTankKeg v_arg1 ExpPack 1.0 ExpPack 1.0
AnimationStateMachine.copyState ger_miniTankKeg v_arg1 ExpPack 1.0 ExpPack 1.0

AnimationStateMachine.copyState SoccerKick v_arg1 GrenadeAllies 1.0 GrenadeAllies 1.0

AnimationStateMachine.copyState COM_TNT v_arg1 ExpPack 1.0 ExpPack 1.0
AnimationStateMachine.copyState COM_BALL v_arg1 ExpPack 1.0 ExpPack 1.0

AnimationStateMachine.copyState BRI_AT_PIAT v_arg1 Bazooka 1.0 Bazooka 1.0
AnimationStateMachine.copyState GER_AT_PanzerFaust v_arg1 Bazooka 1.0 Bazooka 1.0

AnimationStateMachine.copyState bri_aa_stinger v_arg1 Bazooka 1.0 Bazooka 1.0
AnimationStateMachine.copyState ger_aa_strela v_arg1 Bazooka 1.0 Bazooka 1.0

AnimationStateMachine.copyState bri_pistol_agent v_arg1 Colt 1.0 Colt 1.0
AnimationStateMachine.copyState ger_pistol_agent v_arg1 Colt 1.0 Colt 1.0

AnimationStateMachine.copyState bri_pistol_agent_slot2 v_arg1 Colt 1.0 Colt 1.0
AnimationStateMachine.copyState ger_pistol_agent_slot2 v_arg1 Colt 1.0 Colt 1.0

AnimationStateMachine.copyState BRI_Pistol_Colt v_arg1 Colt 1.0 Colt 1.0
AnimationStateMachine.copyState GER_Pistol_Luger v_arg1 Colt 1.0 Colt 1.0

AnimationStateMachine.copyState BRI_Sniperrifle_LeeEnfield v_arg1 No4 1.0 No4 1.0
AnimationStateMachine.copyState GER_SniperRifle_Gewehr43 v_arg1 No4 1.0 No4 1.0

AnimationStateMachine.copyState BRI_Shotgun v_arg1 No4 1.0 No4 1.0
AnimationStateMachine.copyState GER_Shotgun v_arg1 No4 1.0 No4 1.0

rem *** AT Rifles ***

AnimationStateMachine.copyState bri_at_rifle v_arg1 M249 1.0 M249 1.0
AnimationStateMachine.copyState ger_at_rifle v_arg1 M249 1.0 M249 1.0

rem *** Landmines ***
AnimationStateMachine.copyState bri_landmine v_arg1 Landmine 1.0 Landmine 1.0
AnimationStateMachine.copyState ger_landmine v_arg1 Landmine 1.0 Landmine 1.0

rem *** Supply Drops ***
AnimationStateMachine.copyState NASupplyDrop v_arg1 SmokeGrenade 1.0 SmokeGrenade 1.0

AnimationStateMachine.copyState bri_supplydrop v_arg1 SmokeGrenade 1.0 SmokeGrenade 1.0
AnimationStateMachine.copyState ger_supplydrop v_arg1 SmokeGrenade 1.0 SmokeGrenade 1.0

AnimationStateMachine.copyState bri_vehicledrop v_arg1 SmokeGrenade 1.0 SmokeGrenade 1.0
AnimationStateMachine.copyState ger_vehicledrop v_arg1 SmokeGrenade 1.0 SmokeGrenade 1.0


rem *** GoldenEye 007 Weapons ***

AnimationStateMachine.copyState ProximityMine v_arg1 GrenadeAllies 1.0 GrenadeAllies 1.0