rem ** Front left light ***
ObjectTemplate.addTemplate CarFlare
ObjectTemplate.setPosition -0.65/0.15/1.5

rem *** Front right light ***
ObjectTemplate.addTemplate CarFlare
ObjectTemplate.setPosition 0.65/0.15/1.5

rem ** Rear right light ***
ObjectTemplate.addTemplate CarFlareRear
ObjectTemplate.setPosition 0.65/0.15/-1.5
ObjectTemplate.setRotation 180/0/0

rem *** Rear left light ***
ObjectTemplate.addTemplate CarFlareRear
ObjectTemplate.setPosition -0.65/0.15/-1.5
ObjectTemplate.setRotation 180/0/0

rem ** Rear right brake light ***
ObjectTemplate.addTemplate CarFlareRear
ObjectTemplate.setPosition 1.55/0.15/-1.5
ObjectTemplate.setRotation 180/0/0

rem *** Rear left brake light ***
ObjectTemplate.addTemplate CarFlareRear
ObjectTemplate.setPosition -1.55/0.15/-1.5
ObjectTemplate.setRotation 180/0/0

rem *** Reverse right back light ***
ObjectTemplate.addTemplate CarFlareBack
ObjectTemplate.setPosition 0.00/0.15/-1.5
ObjectTemplate.setRotation 180/0/0

rem *** Reverse left back light ***
ObjectTemplate.addTemplate CarFlareBack
ObjectTemplate.setPosition 0.00/0.15/-1.5
ObjectTemplate.setRotation 180/0/0