cd "C:\Program Files\EA Games\Battlefield 1942"
Echo Ready to begin?
Pause
cls
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault_Nights +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault_Nights +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault_Nights +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault_Nights +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault_Winter +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault_Winter +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault_Winter +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Alpine_Assault_Winter +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Buccaneer_Bay +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Buccaneer_Bay +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Buccaneer_Bay +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Buccaneer_Bay +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Buccaneer_Bay_Nights +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Buccaneer_Bay_Nights +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Buccaneer_Bay_Nights +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Buccaneer_Bay_Nights +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash_Nights +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash_Nights +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash_Nights +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash_Nights +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash_Winter +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash_Winter +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash_Winter +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Coastal_Clash_winter +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Midnight_Mayham +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Midnight_Mayham +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Midnight_Mayham +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Midnight_Mayham_Winter +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Midnight_Mayham_Winter +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Midnight_Mayham_Winter +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Perilous_Port +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Perilous_Port +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Perilous_Port +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Perilous_Port +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Riverside_Rush +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Riverside_Rush +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Riverside_Rush +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Riverside_Rush +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Riverside_Rush_Nights +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Riverside_Rush_Nights +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Riverside_Rush_Nights +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Riverside_Rush_Nights +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Seaside_Skirmish +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Seaside_Skirmish +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Seaside_Skirmish +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Seaside_Skirmish +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Seaside_Skirmish_Nights +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Seaside_Skirmish_Nights +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Seaside_Skirmish_Nights +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Seaside_Skirmish_Nights +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Sunset_Showdown +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Sunset_Showdown +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Sunset_Showdown +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Sunset_Showdown +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Victory_Village +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Victory_Village +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Victory_Village +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Victory_Village +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Victory_Village_Nights +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Victory_Village_Nights +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Victory_Village_Nights +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Victory_Village_Nights +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Wicked_Wake +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Wicked_Wake +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Wicked_Wake +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Wicked_Wake +gamePlayMode tdm +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Wicked_Wake_Nights +gamePlayMode Conquest +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Wicked_Wake_Nights +gamePlayMode Coop +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Wicked_Wake_Nights +gamePlayMode Ctf +game bfheroes
BF1942.exe +getContentCRC 1 +hostServer 1 +restart 1 +level Wicked_Wake_Nights +gamePlayMode tdm +game bfheroes