rem *** Randomized Customization Items. This replaces kit parts and also remains on soldiers after death. ***

rem *** Pets ***
ObjectTemplate.addTemplate ger_PetItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** BackPacks ***
ObjectTemplate.addTemplate Ger_BackPackItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** Helmets ***
ObjectTemplate.addTemplate Ger_HelmetItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** FaceItems ***
ObjectTemplate.addTemplate ger_FaceItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** Waist Items ***
ObjectTemplate.addTemplate ger_WaistItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3


rem *** Feet Items ***
ObjectTemplate.addTemplate ger_FeetItem
ObjectTemplate.setIsFirstPersonPart 0
ObjectTemplate.setRandomGeometries 3