rem
rem *** "TSun" of primitive LensFlare ***
rem
ObjectTemplate.create LensFlare TSun11
ObjectTemplate.setLensFlareCount 13
ObjectTemplate.setCoronaCount 4
ObjectTemplate.initLensFlares
ObjectTemplate.setOcclusionQuadWidthHeight 400 400
REM
REM *** Falre no:0 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 0
ObjectTemplate.setFlareSize 0.5 0
ObjectTemplate.setFlaresize2 1 0
ObjectTemplate.setFlareRot 0 0
ObjectTemplate.setFlareColor 200/255/255/55 0
ObjectTemplate.setFlareColor2 200/100/50/10 0
REM
REM *** Falre no:1 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 1
ObjectTemplate.setFlareSize 0.5 1
ObjectTemplate.setFlaresize2 1 1
ObjectTemplate.setFlareRot 0 1
ObjectTemplate.setFlareColor 200/255/255/55 1
ObjectTemplate.setFlareColor2 200/100/50/10 1
REM
REM *** Falre no:2 > LittleDot ***
REM
ObjectTemplate.setFlareTexture ring5.tga 2
ObjectTemplate.setFlareSize 0.5 2
ObjectTemplate.setFlaresize2 1 2
ObjectTemplate.setFlareRot 0 2
ObjectTemplate.setFlareColor 200/255/255/55 2
ObjectTemplate.setFlareColor2 200/100/50/10 2
REM
REM *** Falre no:3 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 3
ObjectTemplate.setFlareSize 0.5 3
ObjectTemplate.setFlaresize2 1 3
ObjectTemplate.setFlareRot 0 3
ObjectTemplate.setFlareColor 200/255/255/55 3
ObjectTemplate.setFlareColor2 200/100/50/10 3
REM
REM *** Falre no:4 :Twins***
REM
ObjectTemplate.setFlareTexture ring5.tga 4
ObjectTemplate.setFlareSize 0.5 4
ObjectTemplate.setFlaresize2 1 4
ObjectTemplate.setFlareRot 0 4
ObjectTemplate.setFlareColor 200/255/255/55 4
ObjectTemplate.setFlareColor2 200/100/50/10 4
REM
REM *** Falre no:5 :Twins***
REM
ObjectTemplate.setFlareTexture ring5.tga 5
ObjectTemplate.setFlareSize 0.5 5
ObjectTemplate.setFlaresize2 1 5
ObjectTemplate.setFlareRot 0 5
ObjectTemplate.setFlareColor 200/255/255/55 5
ObjectTemplate.setFlareColor2 200/100/50/10 5
REM
REM *** Falre no:6 > littleDotty1 big***
REM
ObjectTemplate.setFlareTexture ring5.tga 6
ObjectTemplate.setFlareSize 0.5 6
ObjectTemplate.setFlaresize2 1 6
ObjectTemplate.setFlareRot 0 6
ObjectTemplate.setFlareColor 200/255/255/55 6
ObjectTemplate.setFlareColor2 200/100/50/10 6
REM
REM *** Falre no:7 > littledotty2 smaller***
REM
ObjectTemplate.setFlareTexture ring5.tga 7
ObjectTemplate.setFlareSize 0.5 7
ObjectTemplate.setFlaresize2 1 7
ObjectTemplate.setFlareRot 0 7
ObjectTemplate.setFlareColor 200/255/255/55 7
ObjectTemplate.setFlareColor2 200/100/50/10 7
REM
REM *** Falre no:8 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 8
ObjectTemplate.setFlareSize 0.5 8
ObjectTemplate.setFlaresize2 1 8
ObjectTemplate.setFlareRot 0 8
ObjectTemplate.setFlareColor 200/255/255/55 8
ObjectTemplate.setFlareColor2 200/100/50/10 8
REM
REM *** Falre no:9 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 9
ObjectTemplate.setFlareSize 0.5 9
ObjectTemplate.setFlaresize2 1 9
ObjectTemplate.setFlareRot 0 9
ObjectTemplate.setFlareColor 200/255/255/55 9
ObjectTemplate.setFlareColor2 200/100/50/10 9
REM
REM *** Falre no:10 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 10
ObjectTemplate.setFlareSize 0.5 10
ObjectTemplate.setFlaresize2 1 10
ObjectTemplate.setFlareRot 0 10
ObjectTemplate.setFlareColor 200/255/255/55 10
ObjectTemplate.setFlareColor2 200/100/50/10 10
REM
REM *** Falre no:11 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 11
ObjectTemplate.setFlareSize 0.5 11
ObjectTemplate.setFlaresize2 1 11
ObjectTemplate.setFlareRot 0 11
ObjectTemplate.setFlareColor 200/255/255/55 11
ObjectTemplate.setFlareColor2 200/100/50/10 11
REM
REM *** Falre no:12 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 12
ObjectTemplate.setFlareSize 0.5 12
ObjectTemplate.setFlaresize2 1 12
ObjectTemplate.setFlareRot 0 12
ObjectTemplate.setFlareColor 200/255/255/55 12
ObjectTemplate.setFlareColor2 200/100/50/10 12
REM
REM *** Corona no:0 ***
REM
ObjectTemplate.setCoronaTexture sunflare0.tga 0
ObjectTemplate.setCoronaSize 5 0
ObjectTemplate.setCoronasize2 10 0
ObjectTemplate.setCoronaRot 0.1 0
ObjectTemplate.setCoronaColor 255/255/255/200 0
ObjectTemplate.setCoronaColor2 255/255/255/200 0
REM
REM *** Corona no:1 - Red aura***
REM
ObjectTemplate.setCoronaTexture sunflare9.tga 1
ObjectTemplate.setCoronaSize 4 1
ObjectTemplate.setCoronasize2 8 1
ObjectTemplate.setCoronaRot -1 1
ObjectTemplate.setCoronaColor 250/50/0/50 1
ObjectTemplate.setCoronaColor2 250/50/0/50 1
REM
REM *** Corona no:2 Streaks ***
REM
ObjectTemplate.setCoronaTexture sunflare6.tga 2
ObjectTemplate.setCoronaSize 6 2
ObjectTemplate.setCoronaSize2 7 2
ObjectTemplate.setCoronaRot 0.2 2
ObjectTemplate.setCoronaColor 250/225/225/75 2
ObjectTemplate.setCoronaColor2 250/225/225/75 2
REM
REM *** Corona no:3 Disc ***
REM
ObjectTemplate.setCoronaTexture SunDisc.tga 3
ObjectTemplate.setCoronaSize 1.5 3
ObjectTemplate.setCoronasize2 1.5 3
ObjectTemplate.setCoronaRot 0.1 3
ObjectTemplate.setCoronaColor 255/255/255/200 3
ObjectTemplate.setCoronaColor2 255/255/255/200 3