rem
rem *** "TSun" of primitive LensFlare ***
rem
ObjectTemplate.create LensFlare TSun3
ObjectTemplate.setLensFlareCount 13
ObjectTemplate.setCoronaCount 3
ObjectTemplate.initLensFlares
ObjectTemplate.setOcclusionQuadWidthHeight 200 200
REM
REM *** Falre no:1 ***
REM
ObjectTemplate.setFlareTexture ring6.tga 1
ObjectTemplate.setFlareSize 5 1
ObjectTemplate.setFlareScale 20 1
ObjectTemplate.setFlareRot 0 1
ObjectTemplate.setFlareColor 255/235/235/150 1
ObjectTemplate.setFlareDistFadeScale -0.9 1
REM
REM *** Falre no:2 ***
REM
ObjectTemplate.setFlareTexture ring3.tga 2
ObjectTemplate.setFlareSize 10 2
ObjectTemplate.setFlareScale -10 2
ObjectTemplate.setFlareRot 0 2
ObjectTemplate.setFlareColor 255/255/255/255 2
rem ObjectTemplate.setFlareDistFadeScale 0.5 2
REM
REM *** Falre no:3 > LittleDot***
REM
ObjectTemplate.setFlareTexture ring6.tga 3
ObjectTemplate.setFlareSize 3 3
ObjectTemplate.setFlareScale -1.5 3
ObjectTemplate.setFlareRot 0 3
ObjectTemplate.setFlareColor 255/255/255/100 3
ObjectTemplate.setFlareDistFadeScale 0.5 3
REM
REM *** Falre no:4 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 4
ObjectTemplate.setFlareSize 0.8 4
ObjectTemplate.setFlareScale 1.5 4
ObjectTemplate.setFlareRot 0 4
ObjectTemplate.setFlareColor 255/255/255/155 4
REM
REM *** Falre no:5 :Twins***
REM
ObjectTemplate.setFlareTexture ring6.tga 5
ObjectTemplate.setFlareSize 2 5
ObjectTemplate.setFlareScale -2 5
ObjectTemplate.setFlareRot 0 5
ObjectTemplate.setFlareColor 50/50/150/50 5
ObjectTemplate.setFlareDistFadeScale 0.5 5
REM
REM *** Falre no:6 :Twins***
REM
ObjectTemplate.setFlareTexture ring3.tga 6
ObjectTemplate.setFlareSize 0 6
ObjectTemplate.setFlareScale 3 6
ObjectTemplate.setFlareRot 1 6
ObjectTemplate.setFlareColor 255/255/255/100 6
ObjectTemplate.setFlareDistFadeScale 1 6
REM
REM *** Falre no:7 > littleDotty1 big***
REM
ObjectTemplate.setFlareTexture ring6.tga 7
ObjectTemplate.setFlareSize 0.2 7
ObjectTemplate.setFlareScale 0.4 7
ObjectTemplate.setFlareRot 0 7
ObjectTemplate.setFlareColor 255/150/0/150 7
REM
REM *** Falre no:8 > littledotty2 smaller***
REM
ObjectTemplate.setFlareTexture ring3.tga 8
ObjectTemplate.setFlareSize 0.1 8
ObjectTemplate.setFlareScale 0.3 8
ObjectTemplate.setFlareRot 0 8
ObjectTemplate.setFlareColor 255/255/150/200 8
REM
REM *** Falre no:9 ***
REM
ObjectTemplate.setFlareTexture ring6.tga 9
ObjectTemplate.setFlareSize 0.5 9
ObjectTemplate.setFlareScale 1 9
ObjectTemplate.setFlareRot 0 9
ObjectTemplate.setFlareColor 200/255/255/55 9
ObjectTemplate.setFlareDistFadeScale 0.4 9
REM
REM *** Falre no:10 ***
REM
ObjectTemplate.setFlareTexture ring3.tga 10
ObjectTemplate.setFlareSize 0.75 10
ObjectTemplate.setFlareScale 1 10
ObjectTemplate.setFlareRot 0 10
ObjectTemplate.setFlareColor 255/255/255/100 10
REM
REM *** Falre no:11 ***
REM
ObjectTemplate.setFlareTexture ring6.tga 11
ObjectTemplate.setFlareSize 1 11
ObjectTemplate.setFlareScale 2 11
ObjectTemplate.setFlareRot 0 11
ObjectTemplate.setFlareColor 255/255/255/50 11
REM
REM *** Falre no:12 ***
REM
ObjectTemplate.setFlareTexture ring3.tga 12
ObjectTemplate.setFlareSize 0.4 12
ObjectTemplate.setFlareScale 0.8 12
ObjectTemplate.setFlareRot 0 12
ObjectTemplate.setFlareColor 255/255/255/40 12
REM
REM *** Falre no:13 ***
REM
ObjectTemplate.setFlareTexture ring6.tga 13
ObjectTemplate.setFlareSize 0.5 13
ObjectTemplate.setFlareScale 0 13
ObjectTemplate.setFlareRot 0 13
ObjectTemplate.setFlareColor 200/255/255/40 13
REM
REM *** Corona no:0 ***
REM
ObjectTemplate.setCoronaTexture sunflare0.tga 0
ObjectTemplate.setCoronaSize 15 0
ObjectTemplate.setCoronaScale 2 0
ObjectTemplate.setCoronaRot 0.1 0
ObjectTemplate.setCoronaColor 255/255/255/200 0
REM
REM *** Corona no:1 ***
REM
ObjectTemplate.setCoronaTexture sunflare6.tga 1
ObjectTemplate.setCoronaSize 6 1
ObjectTemplate.setCoronaScale 5 1
ObjectTemplate.setCoronaRot 0.1 1
ObjectTemplate.setCoronaColor 250/250/250/50 1
REM
REM *** Corona no:2 - Red aura***
REM
ObjectTemplate.setCoronaTexture sunflare9.tga 2
ObjectTemplate.setCoronaSize 5 2
ObjectTemplate.setCoronaScale 40 2
ObjectTemplate.setCoronaRot -1 2
ObjectTemplate.setCoronaColor 200/50/0/100 2