rem
rem *** "TSun" of primitive LensFlare ***
rem
ObjectTemplate.create LensFlare TSun6
ObjectTemplate.setLensFlareCount 9
ObjectTemplate.setCoronaCount 3
ObjectTemplate.initLensFlares
ObjectTemplate.setOcclusionQuadWidthHeight 100 100
REM
REM *** Falre no:0 ***
REM
ObjectTemplate.setFlareTexture ring3.tga 0
ObjectTemplate.setFlareSize 3 0
ObjectTemplate.setFlareSize2 2 0
ObjectTemplate.setFlareRot 0 0
ObjectTemplate.setFlareColor 255/255/100/50 0
objectTemplate.setFlareColor2 255/255/100/25 0
REM
REM *** Falre no:1 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 1
ObjectTemplate.setFlareSize 3 1
ObjectTemplate.setFlareSize2 1 1
ObjectTemplate.setFlareRot 0 1
ObjectTemplate.setFlareColor 255/255/255/10 1
ObjectTemplate.setFlareColor2 240/240/240/40 1
REM
REM *** Falre no:2 > LittleDot***
REM
ObjectTemplate.setFlareTexture ring3.tga 2
ObjectTemplate.setFlareSize 0.5 2
ObjectTemplate.setFlareSize2 1 2
ObjectTemplate.setFlareRot 0 2
ObjectTemplate.setFlareColor 255/255/255/100 2
objectTemplate.setFlareColor2 255/255/255/50 2
REM
REM *** Falre no:3 ***
REM
ObjectTemplate.setFlareTexture ring4.tga 3
ObjectTemplate.setFlareSize 0.8 3
ObjectTemplate.setFlareSize2 1.5 3
ObjectTemplate.setFlareRot 0 3
ObjectTemplate.setFlareColor 255/255/255/75 3
ObjectTemplate.setFlareColor2 255/100/100/50 3
REM
REM *** Falre no:4 :Twins***
REM
ObjectTemplate.setFlareTexture ring4.tga 4
ObjectTemplate.setFlareSize 1 4
ObjectTemplate.setFlareSize2 -2 4
ObjectTemplate.setFlareRot 0 4
ObjectTemplate.setFlareColor 255/255/255/25 4
ObjectTemplate.setFlareColor2 100/255/0/0 4
REM
REM *** Falre no:5 :Twins***
REM
ObjectTemplate.setFlareTexture ring5.tga 5
ObjectTemplate.setFlareSize 1 5
ObjectTemplate.setFlareSize2 -3 5
ObjectTemplate.setFlareRot 1 5
ObjectTemplate.setFlareColor 255/255/255/0 5
ObjectTemplate.setFlareColor2 255/0/200/25 5
REM
REM *** Falre no:6 > littleDotty1 big***
REM
ObjectTemplate.setFlareTexture ring6.tga 6
ObjectTemplate.setFlareSize 0.2 6
ObjectTemplate.setFlareSize2 0.4 6
ObjectTemplate.setFlareRot 0 6
ObjectTemplate.setFlareColor 255/255/255/150 6
ObjectTemplate.setFlareColor 255/255/255/150 6
REM
REM *** Falre no:7 > littledotty2 smaller***
REM
ObjectTemplate.setFlareTexture ring6.tga 7
ObjectTemplate.setFlareSize 0.1 7
ObjectTemplate.setFlareSize2 0.3 7
ObjectTemplate.setFlareRot 0 7
ObjectTemplate.setFlareColor 255/255/255/200 7
ObjectTemplate.setFlareColor2 255/255/255/50 7
REM
REM *** Falre no:8 ***
REM
ObjectTemplate.setFlareTexture ring5.tga 8
ObjectTemplate.setFlareSize 0.5 8
ObjectTemplate.setFlareSize2 1 8
ObjectTemplate.setFlareRot 1 8
ObjectTemplate.setFlareColor 255/255/255/55 8
ObjectTemplate.setFlareColor2 255/255/255/5 8
REM
REM *** Corona no:0 ***
REM
ObjectTemplate.setCoronaTexture sunflare7.tga 0
ObjectTemplate.setCoronaSize 2 0
ObjectTemplate.setCoronaSize2 1 0
ObjectTemplate.setCoronaRot 0 0
ObjectTemplate.setCoronaColor 255/255/200/225 0
ObjectTemplate.setCoronaColor2 250/250/200/170 0
REM
REM *** Corona no:1 - Red aura***
REM
ObjectTemplate.setCoronaTexture sunflare9.tga 1
ObjectTemplate.setCoronaSize 5 1
ObjectTemplate.setCoronaSize2 5 1
ObjectTemplate.setCoronaRot 0 1
ObjectTemplate.setCoronaColor 255/150/0/100 1
ObjectTemplate.setCoronaColor2 255/150/0/100 1
REM
REM *** Corona no:2 Disc ***
REM
ObjectTemplate.setCoronaTexture SunDisc.tga 2
ObjectTemplate.setCoronaSize 1.5 2
ObjectTemplate.setCoronasize2 1.5 2
ObjectTemplate.setCoronaRot 0.1 2
ObjectTemplate.setCoronaColor 255/255/255/200 2
ObjectTemplate.setCoronaColor2 255/255/255/200 2